version: '3.7'

services:
  web:
    env_file: 
      - env_file
    build: .
    command: gunicorn --worker-tmp-dir /dev/shm --log-file=- -w 2 -b :5000 "hbdeal.app:initialize_app()"
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes: 
      - ~/mongo/data:/data/db